private_companies <- c(
  "53. COWI A/S, Division 1",
  "48. Epinion A/S",
  "44. PLS RAMBØLL Management A/S",
  "57. CASA",
  "72. Copenhagen Economics",
  "116. NIRAS",
  "162. Teknologisk Institut – Center for Analyse og Erhvervsfremme",
  "173. Capacent A/S",
  "224. Deloitte Consulting, Deloitte, Statsautoriseret Revisionspartnerselskab",
  "243. Oxford Research A/S",
  "252. Danica Kommunikation - Analyseenheden",
  "293. McKinsey & Company",
  "307. Brøndum & Fliess A/S",
  "329. Incentive",
  "318. Mploy A/S",
  "364. Advice A/S",
  "365. DM Partner A/S",
  "374. Nykredit, Risikostyring",
  "387. Moos-Bjerre & Lange ApS",
  "402. Metrica APS",
  "411. BDO Consulting",
  "441. Last Mile P/S",
  "445. DAMVAD Analytics",
  "461. Marselisborg",
  "475. IMS Health Technology Solutions Denmark A/S",
  "480. Højbjerre Brauer Schultz",
  "481. IRIS Group",
  "488. Analyse & Tal")